env: sandbox

image:
  devRepo: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  name: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  tag: latest
  pullPolicy: Always

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "50Mi"
    cpu: "10m"
  limits:
    cpu: "30m"
    memory: "100Mi"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 200
  cpuPercentage: 250
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

log:
  level: debug

sftp:
  directory: .
  test:
    enabled: true

retry:
  delay: 3600000

cleanup:
  delay: 24
  duration: 720

gcp:
  project: ras-rm-sandbox
  bucket:
    name: print-file
    prefix: ""
  topic: print-file
  subscription: print-file
