// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	pkg "github.com/ONSdigital/ras-rm-print-file/pkg"
	mock "github.com/stretchr/testify/mock"
)

// Printer is an autogenerated mock type for the Printer type
type Printer struct {
	mock.Mock
}

// Process provides a mock function with given fields: filename, printFile
func (_m *Printer) Process(filename string, printFile *pkg.PrintFile) error {
	ret := _m.Called(filename, printFile)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *pkg.PrintFile) error); ok {
		r0 = rf(filename, printFile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReProcess provides a mock function with given fields: printFileRequest
func (_m *Printer) ReProcess(printFileRequest *pkg.PrintFileRequest) error {
	ret := _m.Called(printFileRequest)

	var r0 error
	if rf, ok := ret.Get(0).(func(*pkg.PrintFileRequest) error); ok {
		r0 = rf(printFileRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
