// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Upload is an autogenerated mock type for the Upload type
type Upload struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Upload) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields:
func (_m *Upload) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadFile provides a mock function with given fields: filename, contents
func (_m *Upload) UploadFile(filename string, contents []byte) error {
	ret := _m.Called(filename, contents)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(filename, contents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
